### ISSUE TITLE
Let's add e2e test!

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#142]
**Objective**: The goal of this issue is to implement e2e test harness for the NodeGoat, so that it would be easier for project contributors to validate PRs and ensure that no unexpected side effects / defects arise due to enhancements. 

====  
As agreed with @ckarande I will create a PR to add e2e test for NodeGoat using Cypress. 

The idea is to cover most of the UI, so we can test all the features before merging PRs. 

### Targets and assigneed:
- [x] /tutorial (@koolTheba)
- [x] / (dashboard) (@koolTheba)
- [x] /learn (@koolTheba)
- [x] /research (@koolTheba)
- [x] General stuff (404, menus, etc..) (@ulisesGascon)
- [x] /signup (@ulisesGascon)
- [x] /logout (@ulisesGascon)
- [x] /memos (@ulisesGascon)
- [x] /contributions (@ulisesGascon)
- [x] /allocations (@ulisesGascon)
- [x] /profile (@ulisesGascon) 
- [x] /login (@ulisesGascon)
- [x] /benefits (@ulisesGascon)

**Comment by ckarande** [comment]
@UlisesGascon  You have captured its scope precisely! Thank you for opening this issue and offering to assist on it.

**Comment by UlisesGascon** [comment]
@ckarande  just a spoiler 📽
cc: @lirantal @jesusprubio

![ezgif-3-5fce08977a27](https://user-images.githubusercontent.com/5110813/59146597-96670100-89f0-11e9-99a7-1951cc47b78b.gif)


_This is just `/login` behaviour. I will clean the code and left an open PR for you to check while I keep working on it. The idea is to gather early feedback._

**Comment by ckarande** [comment]
@UlisesGascon Looks great, You rock! Yes, I will follow the open PR. Great work.

**Comment by lirantal** [comment]
Great stuff @UlisesGascon!

We should probably describe the purpose of the e2e tests here.
Are they going to test the vulnerabilities or test that the application as-is continues to function as expected to so when we refactor we can ensure that nothing was broken? Seems like the latter but just making sure, and we should update the PR/issue with that goal.

**Comment by ckarande** [comment]
Yes @lirantal, the purpose of these tests is to ensure nothing is broken as we update the project further. @UlisesGascon has some great ideas and graciously offered to assist on working on some long due enhancements. This issue is just a prep work to get the necessary test harness so that it would be easier to validate PRs in future. 

In future, we can extend the cypress test setup to provide a test suite that could assist a user guide allowing them to pass tests as they solve the challenges to fix vulnerabilities. But it is out of scope for this issue.

In either case, it is a good idea to add the purpose of this issue in it's description. Thanks for that suggestion.

**Comment by lirantal** [comment]
Sounds good 👍

**Comment by UlisesGascon** [comment]
Yeah... I agree with @ckarande. The best way is to split the test in two different PRs. The current one for general application behaviour and a separate one for test vulnerabilities. 😄

**Comment by UlisesGascon** [comment]
Good News! @koolTheba will help us with the e2e test too.

:tada: Welcome aboard @kooltheba

**Comment by binarymist** [comment]
Just bear in mind that any security regression tests written will be redundant once [purpleteam](https://gitlab.com/purpleteam-labs) is running over this project. Purpleteam requires no tests to be written, the product is smart enough to know what and how to test without tests being written.

**Comment by UlisesGascon** [comment]
@binarymist awesome!! Thanks for share it 👍

**Comment by ckarande** [comment]
Welcome aboard @KoolTheba 👍 🎉

**Comment by UlisesGascon** [comment]
PR Review needed: _See #143_

**Comment by ckarande** [comment]
@UlisesGascon Awesome! Great work. Thank you. 
I will go over the PR and get back to you if any feedback.

@binarymist @lirantal Great inputs from you so far and feel free to suggest if any thoughts on the PR!

**Comment by lirantal** [comment]
I think would be great to land it with a travis.yml file to make sure we're testing it and it becomes a baseline and we can work out follow-up PRs to refactor for more code clarity etc.

**Comment by lirantal** [comment]
And of course amazing stuff @UlisesGascon! 🌈✨

**Comment by UlisesGascon** [comment]
This is merged to master now ^^
