### ISSUE TITLE
Let's improve build steps and include Travis

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#144]
After the efforts to improve the e2e testing (#142 #143). The next step will be to improve the build steps.

**Ideas**
- [x] Include Travis, so we can run the e2e tests in all the PRs. _See: #147_
- [ ] Migration from Grunt to Npm Scripts 
- [ ] Harmonize the JS Style with [Standard](https://standardjs.com/) and [Prettier](https://prettier.io)
- [ ] Let's add git hooks for linting and testing with [Husky](https://github.com/typicode/husky)

What do you think, @ckarande?

**Comment by ckarande** [comment]
Love it! It would be a very valuable addition. 👍
We should make a release with these features in and before starting on major refactoring at the code level. Thank you.

**Comment by lirantal** [comment]
Sounds great! ✨

I'd advise that we do all of those in their own separate PRs (as smaller units of work as possible) so that we are able to move fast instead of having big-bang PRs that add risk and take a longer time to review.

**Comment by UlisesGascon** [comment]
Great advise @lirantal! I will generate separare PRs ;-)

**Comment by UlisesGascon** [comment]
I started to work in the Grunt refactor. Most of the tasks are simple to relocate as npm scripts. But regarding regression and security tests. Right now we are [using ZAP](https://www.youtube.com/watch?v=IVLpmCtiPZ0&feature=youtu.be&t=2447), as @binarymist [suggested]( https://github.com/OWASP/NodeGoat/issues/142#issuecomment-500380900) maybe we can use [purpleteam](https://gitlab.com/purpleteam-labs). 

My approach to this refactor will be to keep grunt only for current security test until we can start the migration to purpleteam if you agree. What do you think @ckarande @lirantal @koolTheba?

**Comment by ckarande** [comment]
I agree. 👍

**Comment by lirantal** [comment]
Happy to see how this works out as well. Keep up the great work ✨

**Comment by UlisesGascon** [comment]
CLose as duplicated in #148
