### ISSUE TITLE
nodegoat.herokuapp.com not working

### ISSUE THREAD

**Issue by synedra** [OWASP/NodeGoat#165]
I'm getting application errors with any of the documentation links in the README, it looks like your heroku app isn't working.

**Comment by UlisesGascon** [comment]
Hi @synedra! Thanks for alert us about it, seems like the service is down.

@ckarande can you help us? Maybe we can have a look together, I guess there is a problem with the [Dynos policies once restart](https://devcenter.heroku.com/articles/dynos#automatic-dyno-restarts). 


> The Common Runtime implements an incremental backoff policy for crashing dynos:
>- The first time a dyno crashes, it will be restarted immediately.
>-  If the dyno crashes again, it will be subject to a cool-off period before a restart is attempted.
>- The first cool-off period is up to 20 minutes, the next one is up to 40 minutes, then up to 60 minutes, up to 180 minutes and finally up to 320 minutes.
>- After the 320 minute cool-off period is reached, restart attempts happen every 320 minutes.
>- The cool-off period will be reset when the dyno starts correctly, or when you push a new release to your app, or when you restart your app (for example, by typing heroku restart), or when you scale your dynos to 0 and then scale them back up again.
>
> The Private Spaces Runtime does not have a backoff policy. When a dyno crashes it will be continuously restarted with no cool-off period.

In [OSW](https://github.com/OSWeekends) we had a system in place to restart and update the machine by default with Kubernetes. If we need devops support I can ask @jvidal-sysadmin for support :-)

**Comment by ckarande** [comment]
@synedra thanks for reporting it. 
@UlisesGascon thanks for the information. I had to manually deploy the app and seems to have fixed it but I will monitor the automated deploy process on changes to master and dig more if the issue continues.
