### ISSUE TITLE
Need help creating SQL injection queries

### ISSUE THREAD

**Issue by synedra** [OWASP/NodeGoat#166]

**Comment by synedra** [comment]
I'm trying to use NodeGoat to teach customers about security issues, but all of the examples assume I'm going to be using Javascript.  How can I make the same call with a shell script or wget/http, so they can understand what's needed?  I don't have the ability to use a Javascript enabled page although I suppose I could write a node server to attack the system.

**Comment by ckarande** [comment]
Thanks for considering NodeGoat for your training @synedra. Current Nodegoat implementation uses server side templates to generate UI and doesn't expose REST APIs.  So it doesn't provide an ability to access endpoints with shell script/wget as you are looking for.

We have an issue #38 to start supporting different architectures, but it is planned for a later release (1.6.0).
