### ISSUE TITLE
Heroku - mLab MongoDB Add-on Discontinued

### ISSUE THREAD

**Issue by Whamo12** [OWASP/NodeGoat#212]
The mLab MongoDB Add-on will be shutting down on November 10th and may inadvertently affect the `Deploy to Heroku` functionality.  The following documentation contains specific information.

https://docs.mlab.com/shutdown-of-heroku-add-on/

**Comment by ckarande** [comment]
@Whamo12 Thanks for the information. We should migrate to MongoDB Atlas as suggested here:
https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/

**Comment by rcowsill** [comment]
Something to bear in mind is that the Atlas M0 tier doesn't support server-side javascript (From: [Atlas M0 (Free Tier)... Limitations](https://docs.atlas.mongodb.com/reference/free-shared-limitations/#operational-limitations)).

There's currently a `$where` query in allocations-dao.js, which is used to demonstrate NoSQL injection vulnerabilities:

https://github.com/OWASP/NodeGoat/blob/5b6a3078b31dc346e5ce7b86837d6abbe7a18bbd/app/data/allocations-dao.js#L78

**Comment by rcowsill** [comment]
I've made a task list for the work to resolve this issue. Feedback is welcome on whether this is the right approach, or if I missed anything important.

The work to fix the "Deploy to Heroku" button can be done by any contributor:
- [ ] Remove mongolab:sandbox addon from app.json
- [ ] Add a MONGODB_URI env variable to app.json (required, default `""`)
- [ ] Remove reference to the current mLab database from config/env/all.js
- [ ] Remove support for MONGOLAB_URI in config/env/all.js (only needed for the mongolab addon)
- [ ] Update heroku deploy instructions in README.md to cover database setup
- [ ] Update tutorial for `A1 - Injection` to say NoSQL injection is blocked on deployments using Atlas M0

These tasks can only be done by members of the core project team:
- [ ] Create a new Atlas account, database and user for http://nodegoat.herokuapp.com/
- [ ] Update http://nodegoat.herokuapp.com/ to use the new Atlas DB and user
- [ ] Once the tasks above and #213 are resolved, shut down the mLab database

I'd be happy to make a PR for the first set of tasks (if no-one's already lined up to do it).

**Comment by rcowsill** [comment]
Reminder: mongolab heroku addons are due to be deleted on Tuesday, November 10th. When that happens, any mLab databases still attached to a mongolab heroku addon will be deleted.

Hopefully the database for http://nodegoat.herokuapp.com/ has already been detached from its addon, otherwise the app will go down when the database gets deleted on Tuesday.

**Comment by ckarande** [comment]
@rcowsill Thank you for staying on top of this and the PR. @Whamo12, appreciate your reporting this issue. 

Merged the PR. I wanted to provide default Altas DB URL for a quick start for those who don't have it or willing to create an account on Atlas. Hence restored the all.js as before except with Atlas DB URL. We can revise this logic, if any suggestions.

Closing this issue.
