### ISSUE TITLE
Travis config warnings

### ISSUE THREAD

**Issue by rcowsill** [OWASP/NodeGoat#219]
This is a very minor issue, but the travis dashboard lists some warnings for the config file:
```
root: deprecated key sudo (The key `sudo` has no effect anymore.)
cache: unknown key override ([npm ci, npm run cy ...])
root: missing dist, using the default xenial
root: missing os, using the default linux
```
I have [a commit](https://github.com/OWASP/NodeGoat/compare/master...rcowsill:fix/travis-warnings#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485) ready for PR that removes the unknown/deprecated lines and adds the missing ones.

**Comment by ckarande** [comment]
@rcowsill Thanks..Also notices your message on Gitter regarding Github Actions. In case this is still relevant, please make a PR.

**Comment by rcowsill** [comment]
@ckarande I submitted a PR (#223) as the change was ready to go. That said, it's not essential if the project is switched over to GitHub Actions CI. Feel free to close this issue and PR #223 in that case.
