### ISSUE TITLE
Unexpected path traversal vulnerability

### ISSUE THREAD

**Issue by rcowsill** [OWASP/NodeGoat#232]
Looking at [NodeGoat's results on LGTM.com](https://lgtm.com/projects/g/OWASP/NodeGoat?mode=list), alongside the expected vulnerabilities there are some more alerts. Most are minor issues, but one is for this unexpected vulnerability:

https://lgtm.com/projects/g/OWASP/NodeGoat?mode=list&tag=external%2Fcwe%2Fcwe-022

The `/tutorial/:page` route passes the user-controlled `page` parameter directly to `res.render`, which is warned against in the express documentation:

> (http://expressjs.com/en/4x/api.html#res.render)
**NOTE:** The view argument performs file system operations like reading a file from disk and evaluating Node.js modules, and as so for security reasons should not contain input from the end-user.

For example, requesting `/tutorial/layout` renders the header and sidebar with no content. That's not too bad, but it's also possible to use relative paths to return any ".html" file on the server. An attacker could also trick express into trying to load any installed node module as a view engine.

**Comment by lirantal** [comment]
Sounds like this is a good opportunity to in fact extend the list of vulnerabilities we cover with a path traversal one. I think that instead of fixing it, let's make it a thing and add a tutorial step for it?

**Comment by rcowsill** [comment]
It's a good idea to extend the vulnerability list to include this, but the issue currently affects the tutorial section of the app. I think of the tutorial pages as OWASP documentation that's just bundled into the app for convenience. As such, I consider them outside the scope of the "vulnerable app".

Rather than documenting this vulnerability as is, I think it would be better to fix it in the tutorial section, then add a new instance of it inside the app proper.

For example, this could be a new "help" section in the dashboard sidebar. That would be structured like the tutorial pages, but with just a few sections of instructions aimed at users of the retirement savings app.

**Comment by lirantal** [comment]
I agree. We should do both:
1. Fix this issue on the tutorial
2. Add a static public pages view such as a help section like you suggested, and we make that vulnerable.

Would you like to proceed with either/both?
