### ISSUE TITLE
A9 - Wrong url, to be removed

### ISSUE THREAD

**Issue by GeniaT** [OWASP/NodeGoat#234]
Hello,

The 6th link [bithound](http://www.bithound.io/) should be removed from the [page ](https://nodegoat.herokuapp.com/tutorial/a9)as it's not a Nodejs service anymore but a casino website. 

Cheers,
Genia.

**Comment by rcowsill** [comment]
Good catch! Based on archive.org it looks like bithound shut down in 2018.

Looking through the rest of that list, nodesecurity.io (link 1) is a holding site. It look like it was run by a company that then got acquired by NPM.  Their advisories were integrated into npmjs.com, so I think https://www.npmjs.com/advisories is an appropriate replacement link.

The same company also seemed to be involved with the requiresafe module. That's still on NPM, but has been deprecated and not been updated for five years. It continued for a while as the [nsp module](https://www.npmjs.com/package/nsp), before being [shut down in 2018](https://web.archive.org/web/20180703174622/https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting). That tool's functionality was built into npm v6: https://medium.com/npm-inc/announcing-npm-6-5d0b1799a905. We could link to the [NPM audit docs](https://docs.npmjs.com/cli/v7/commands/npm-audit) as a replacement.

The "npm outdated" link is broken too; it loads the tutorial page again in a new tab. That could be updated with links to https://docs.npmjs.com/cli/v7/commands/npm-outdated and https://classic.yarnpkg.com/en/docs/cli/outdated.

It might also be a good idea to add a link to dependabot too, eg: https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-dependabot-security-updates
