### ISSUE TITLE
Not working with MongoDB 5

### ISSUE THREAD

**Issue by ctownshend** [OWASP/NodeGoat#264]
Error [MongoError]: Unsupported OP_QUERY command: insert. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal

Steps to repro
docker-compose build
docker-compose up

Latest mongodb is 5 and I think it is incompatible with the nodegoat project as it stands.

Overall wondering where this project is at. Seems like it hasn't been touched for a while.  If anyone from the project team reads this. I am happy to get involved to assist.

**Comment by mcloots** [comment]
Go to docker-compose.yml and change 'mongo:latest' to 'mongo:4.2'.
Don't forget to execute 'docker compose down' before rebuilding and starting again.

Cheers!

**Comment by natgriffiths** [comment]
I changed to Mongo:4.2 and got the following error:
nodegoat_mongo_1 exited with code 14
web_1    | nc: bad address 'mongo'

Cheers

**Comment by StengoS** [comment]
> I changed to Mongo:4.2 and got the following error: nodegoat_mongo_1 exited with code 14 web_1 | nc: bad address 'mongo'
> 
> Cheers

I ran into the same issue after changing `mongo:latest` to `mongo:4.2`, but then I looked again and made sure to run `docker compose down` before building and starting again.

**Comment by lirantal** [comment]
Fixed in PR #265
