### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by noama163** [OWASP/NodeGoat#271]
Hey,
After installing everything setting the MONGODB_URI to the correct one from Atlas and running everything.
For some reason when I run:
npm run db:seed

It outputs this:
> owasp-nodejs-goat@1.3.0 db:seed
> cross-env NODE_ENV=test grunt db-reset

Running "db-reset" task
>> db-reset:
>> Error: Command failed: NODE_ENV=test node artifacts/db-reset.js
>>

**Comment by noama163** [comment]
Also for some reason now it started to say:
sh: cross-env: command not found

I am running:
npm list

And cross-env is not listed there

**Comment by noama163** [comment]
Also tried running the docker version and when I go into the localhost:4000 it states
ERR_EMPTY_RESPONSE

:(

**Comment by lirantal** [comment]
@noama163 can you share if this is still happening to you with the setup?
I see we have both `cross-env` and `grunt` as part of the development dependencies. Can you make sure you install all of them?

**Comment by snow-kluster** [comment]
Error is still happening with both the source and docker versions when trying to setup the app

**Comment by lirantal** [comment]
@snow-kluster can you please provide background on the environment you are testing this with?

**Comment by snow-kluster** [comment]
> @snow-kluster can you please provide background on the environment you are testing this with?

I am using
OS: Ubuntu 22.04
node version: 18.14.2
mongo DB version: 6.0.4
docker version: 23.0.1 

However I was able to fix the issue by adding **"grunt-nodemon"** to the package.json.

**Comment by snow-kluster** [comment]
> You need Mongo 4

Thanks, I fixed the issue. able to setup the application with docker and source.

**Comment by rapPayne** [comment]
@lirantal Is Mongo *version 4* required? In the README, it says we need MongoDB but not version 4 in particular.
