### ISSUE TITLE
Tutorial Guide page is not working

### ISSUE THREAD

**Issue by SamuelNeceda** [OWASP/NodeGoat#273]
![image](https://user-images.githubusercontent.com/69465264/212312074-6d12307c-8efd-405f-8eea-d936f0048be3.png)

**Comment by lukejpreston** [comment]
This error is still occurring
Is there an alternative way to get these documents?

**Comment by snow-kluster** [comment]
Hi it looks like the Heroku page has been take down but the tutorial has not been restored. You can its access the tutorial using the way back machine at [tutorial](https://web.archive.org/web/20200808193639/http://nodegoat.herokuapp.com/tutorial)

**Comment by snow-kluster** [comment]
> This error is still occurring Is there an alternative way to get these documents?

Hi it looks like the Heroku page has been take down but the tutorial has not been restored. You can its access the tutorial using the way back machine at [tutorial](https://web.archive.org/web/20200808193639/http://nodegoat.herokuapp.com/tutorial)

**Comment by snow-kluster** [comment]
Its possible to move away from Heroku and such platforms and host the tutorials here on GitHub using GitHub pages.
If the documentation of the tutorial could be provided, I can write a Gitbook for the tutorials pages.

Would love to here your response

**Comment by lirantal** [comment]
Until we figure out hosting, I've updated the docs to clarify how you can access the tutorial locally.
