### ISSUE TITLE
Separate tutorial from application codebase

### ISSUE THREAD

**Issue by ckarande** [OWASP/NodeGoat#35]
Use [github pages](https://pages.github.com/) or [gitbook](https://github.com/GitbookIO/gitbook) format for tutorial

**Comment by jesusprubio** [comment]
Or even a "doc" folder using Markdown could be enough for now. I think from there we can achieve both these formats.

**Comment by binarymist** [comment]
Is this done @ckarande ?

**Comment by jesusprubio** [comment]
I think @ckarande has almost finished the migration to gitbook, any new about it?

**Comment by ckarande** [comment]
@jesusprubio, @binarymist sorry for the delay in response. I was half way through migration, and other priorities halted it. I would need to pick it up. Any contributions are welcome.

**Comment by binarymist** [comment]
So does this mean the complete tutorials are being deprecated?

**Comment by ckarande** [comment]
I wanted to keep the routes and templates for the doc separate it from the vulnerable app. The gitbook is the most promising option. Would you preserve to keep the existing doc links?

**Comment by binarymist** [comment]
I don't think changing the links will affect me. It's just that the current tutorials look good and seem to be quite functional, so I was just wondering why we needed the change. I'm not really precious either way though. Separating out a little more seems good, but as long as it's still close to the code.

**Comment by jesusprubio** [comment]
I also think it's a good option to separate the code from he tutorial. But it's not a big matter for me any of the two options. I like the tutorials, but I also like the gitbook that @ckarande showed me in the past. The content is the same.

But we need to take a decision to keep pushing :).

**Comment by jboyer2012** [comment]
Haven't seen much movement here. Is there anything I can do to help? I am the strange kind of developer that loves to write documentation. I'd be glad to contribute to an upgrade.

**Comment by ckarande** [comment]
@jboyer2012 thanks for offering to help on documentation. Due to ease on update and convenience to read while working on the app,   we are keeping the  in app documentation as is for now. I will close this issue, but reach out to you while doing  updates in future.
