### ISSUE TITLE
Create Vagrant or Docker setup script

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/NodeGoat#53]
Which will make the set-up and run of NodeGoat easier (For example when running it in a class environment)

**Comment by ckarande** [comment]
That is a great idea. I see the value behind it. Do you have any recommendation on choosing between Vagrant or Docker for this project? Would you like to assist on it?

**Comment by jesusprubio** [comment]
:+1: to docker, I like the idea :smile: , the only steps to get it ready are:
```bash
git clone https://github.com/OWASP/NodeGoat
cd NodeGoat
npm install
npm i -g grunt-cli
grunt db-reset:development
npm start
```

**Comment by ckarande** [comment]
@DinisCruz Can you please review PR #62 and let us know if any suggestions. Thanks.
