### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by binarymist** [OWASP/NodeGoat#55]
Following directions on the README.md...

node -v
v0.10.38
npm -v
2.9.0

From within NodeGoat dir I receive errors:

npm install
 
> kerberos@0.0.12 install 
NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: Leaving directory `NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree

> bson-ext@0.1.7 install NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: g++: Command not found
make: *** [Release/obj.target/bson/ext/bson.o] Error 127
make: Leaving directory `NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node" "--module_name=bson" "--module_path=NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release"
gyp ERR! cwd NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.13.0-24-generic
node-pre-gyp ERR! command "node" "NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
node-pre-gyp ERR! node -v v0.10.38
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=Source/NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release' (1)
make: Entering directory `NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: Leaving directory `NodeGoat/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
dont-sniff-mimetype@0.1.0 node_modules/dont-sniff-mimetype

Then with:
grunt db-reset:development:

Running "db-reset:development" (db-reset) task
>> db-reset:
>> Error: Command failed: js-bson: Failed to load c++ bson extension, using pure JS version
>> js-bson: Failed to load c++ bson extension, using pure JS version
>> js-bson: Failed to load c++ bson extension, using pure JS version
>> js-bson: Failed to load c++ bson extension, using pure JS version
>> 
>> NodeGoat/node_modules/mongodb/lib/server.js:228
>>         process.nextTick(function() { throw err; })
>>                                             ^
>> TypeError: Cannot call method 'dropCollection' of null
>>     at NodeGoat/artifacts/db-reset.js:68:8
>>     at NodeGoat/node_modules/mongodb/lib/mongo_client.js:236:20
>>     at NodeGoat/node_modules/mongodb/lib/db.js:203:14
>>     at null.<anonymous> (NodeGoat/node_modules/mongodb/lib/server.js:226:9)
>>     at g (events.js:180:16)
>>     at emit (events.js:98:17)
>>     at null.<anonymous> (NodeGoat/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:255:68)
>>     at g (events.js:180:16)
>>     at emit (events.js:98:17)
>>     at null.<anonymous> (NodeGoat/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:77:12)
>> js-bson: Failed to load c++ bson extension, using pure JS version
>> js-bson: Failed to load c++ bson extension, using pure JS version
>> js-bson: Failed to load c++ bson extension, using pure JS version
>> js-bson: Failed to load c++ bson extension, using pure JS version
>> 
>> NodeGoat/node_modules/mongodb/lib/server.js:228
>>         process.nextTick(function() { throw err; })
>>                                             ^
>> TypeError: Cannot call method 'dropCollection' of null
>>     at NodeGoat/artifacts/db-reset.js:68:8
>>     at NodeGoat/node_modules/mongodb/lib/mongo_client.js:236:20
>>     at NodeGoat/node_modules/mongodb/lib/db.js:203:14
>>     at null.<anonymous> (NodeGoat/node_modules/mongodb/lib/server.js:226:9)
>>     at g (events.js:180:16)
>>     at emit (events.js:98:17)
>>     at null.<anonymous> (NodeGoat/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:255:68)
>>     at g (events.js:180:16)
>>     at emit (events.js:98:17)
>>     at null.<anonymous> (NodeGoat/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:77:12)

Done, without errors.

npm start

> owasp-nodejs-goat@1.3.0 start NodeGoat
> node server.js

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Error: DB: connect
{ [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONNREFUSED' }

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/usr/bin/npm" "start"
npm ERR! node v0.10.38
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE
npm ERR! owasp-nodejs-goat@1.3.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the owasp-nodejs-goat@1.3.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the owasp-nodejs-goat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls owasp-nodejs-goat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     NodeGoat/npm-debug.log

There is no npm-debug.log

Any ideas?
I'm running a demo of this the day after tomorrow and will be in-flight tomorrow.
Thanks.

**Comment by jesusprubio** [comment]
Hi, update your Node version to 12.x and it should work. I'm using v0.12.2.

**Comment by ckarande** [comment]
@binarymist The errors on `npm install` appear to be just warnings. 

When you ran `grunt db-reset:development`, did you have a local DB mongod running or have a remote DB path set in `config/env/development.js`? It is required for `db-reset` to run properly. 
I have updated README.md with "Create and populate Mongo DB" section to make it more clear.

I don't think your node and npm needs to be upgraded, but let us know how it goes.

**Comment by jesusprubio** [comment]
ping @binarymist? :)

**Comment by binarymist** [comment]
There was a lot of setup work for this to work. I may come back to this, but it's a shame it doesn't work out of the box.

Cheers.

**Comment by ckarande** [comment]
@binarymist We can possibly create a VM that comes with everything packaged together. Besides that, based on your experience with other OWASP or external project of similar kind, can you share ideas on how we could minimize the setup part?

With respect to nodegoat, I am sure user would already have or won't mind installing node and required npm packages. Unfortunately, these type of apps need some backend database to demonstrate injection attacks, and I see installing mongo db could be a pain point. To make it easier, the project supports using a remote db, just by adding its url in the config file. One can create a remote mongo db in few minutes on service as [mongolab](https://mongolab.com/) to eliminate local installation. 

I am sure, there is always room for improvement, and any suggestion or PR are welcome.

Cheers.

**Comment by binarymist** [comment]
Yeah, I think the uptake may be slow without a turn-key solution (bit like owaspbwa). Most people just can't be bothered. I've spent the last couple of weeks in security research and using a bunch of pen test tools. Many of which require some setup and many of which don't even work. This is really frustrating, but sadly quite common. From experience Node projects seem to be even worse.

In saying that, we really do need a Node vulnerable web app and it'd something I'd really like to help with code wise, as I'm fairly intimate with JavaScript and NodeJS. I was hoping to take this to the [workshop](http://v.campjs.com/#holistic-infosec-for-web-developers) I just ran at CampJS in Melbourn, but couldn't afford spending the time on this with an unknown outcome. Instead I created the [Holistic InfoSec for Web Developers](https://github.com/binarymist/HolisticInfoSec-For-WebDevelopers/wiki/BinaryMist-Approach-To-Threat-Modelling) workshop. Time is a problem for me currently though as I'm currently working on my text talk and demo at [WDCNZ](http://www.wdcnz.com/) along with a ton of other stuff. I'll see how much time I get after WDCNZ. I'm thinking of submitting a few more talks this year, but if you think you could use a hand with this, maybe I could help out instead. Thoughts?

**Comment by cktricky** [comment]
We use Docker and provide Vagrant (if thats your preferred method of managing docker instances) over at the Railsgoat project. Seems to work well and address the providing a VM issue.

**Comment by ckarande** [comment]
@binarymist Yes, I agree that painful setup can be a major barrier for project uptake. Based on your feedback, I have added a One-Click heroku deploy option, which requires zero setup. Please go over updated README and let me know your thoughts. 

The workshops you are doing are impressive, and valuable as targeted mainly for developers. Keep it up. Along the way if you feel NodeGoat could be leveraged (with any further improvements), feel free to let us know, or contribute if time permits.

@cktricky , thanks for sharing info on usage of Dockers for RailsGoat. I will check that out. We already have an  issue #53  added by @DinisCruz , proposing implementation on similar lines. A discussion is also ongoing on [project slack channel](https://owasp.slack.com/messages/project-nodegoat/). The RailsGoat implementation is useful for reference in this regard, and I will get in touch with you if any more details needed. Thanks!

**Comment by ckarande** [comment]
Closing the issue now. Please use slack or gitter chat if any comments / feedback
