### ISSUE TITLE
Issues while installing from Dockerfile 

### ISSUE THREAD

**Issue by Ranybaug** [OWASP/NodeGoat#69]
Step 2 : RUN node artifacts/db-reset.js
 ---> Running in cf4359418eff
ERROR: connect
{"name":"MongoError","message":"connect ECONNREFUSED"}
Connected to the database: mongodb://localhost:27017/nodegoat
/usr/src/app/node_modules/mongodb/lib/server.js:231
        process.nextTick(function() { throw err; })
                                            ^
TypeError: Cannot read property 'dropCollection' of null
    at /usr/src/app/artifacts/db-reset.js:66:7
    at /usr/src/app/node_modules/mongodb/lib/mongo_client.js:238:20
    at /usr/src/app/node_modules/mongodb/lib/db.js:242:14
    at null.<anonymous> (/usr/src/app/node_modules/mongodb/lib/server.js:229:9)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:218:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:125:12)
The command '/bin/sh -c node artifacts/db-reset.js' returned a non-zero code: 1

**Comment by binarymist** [comment]
Hi @Ranybaug . That's an error. How did you arrive at this state and what were your exact steps to produce?

**Comment by Ranybaug** [comment]
I ran docker-compose build and got that error shown below : 

>  docker-compose build
mongo uses an image, skipping
Building web
Step 1 : FROM node:0.12-onbuild
# Executing 3 build triggers...
Step 1 : COPY package.json /usr/src/app/
Step 1 : RUN npm install
 ---> Running in d21b334fae2f
npm WARN package.json owasp-nodejs-goat@1.3.0 No README data
npm WARN package.json owasp-nodejs-goat@1.3.0 license should be a valid SPDX license expression
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN optional dep failed, continuing fsevents@1.0.12
npm WARN engine xmlbuilder@8.2.2: wanted: {"node":">=4.0"} (current: {"node":"0.12.14","npm":"2.15.1"})

> utf-8-validate@1.2.1 install /usr/src/app/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/src/app/node_modules/selenium-webdriver/node_modules/ws/node_modules/utf-8-validate/build'
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> bufferutil@1.2.1 install /usr/src/app/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/src/app/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil/build'

> chromedriver@2.21.2 install /usr/src/app/node_modules/chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
Saving to /usr/src/app/node_modules/chromedriver/chromedriver/chromedriver_linux64.zip
Receiving...
Received 821K...
Received 1622K...
Received 2403K...
Received 2629K total.
Extracting zip contents
Copying to target path /usr/src/app/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /usr/src/app/node_modules/chromedriver/lib/chromedriver/chromedriver
dont-sniff-mimetype@0.1.0 node_modules/dont-sniff-mimetype

consolidate@0.12.1 node_modules/consolidate

bcrypt-nodejs@0.0.3 node_modules/bcrypt-nodejs

underscore@1.8.3 node_modules/underscore

validator@3.43.0 node_modules/validator

serve-favicon@2.3.0 node_modules/serve-favicon
├── fresh@0.3.0
├── parseurl@1.3.1
├── etag@1.7.0
└── ms@0.7.1

async@1.5.2 node_modules/async

grunt-concurrent@1.0.1 node_modules/grunt-concurrent
├── pad-stdio@1.0.0 (lpad@1.0.0)
└── async@0.9.2

express-session@1.13.0 node_modules/express-session
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── on-headers@1.0.1
├── parseurl@1.3.1
├── cookie@0.2.3
├── depd@1.1.0
├── crc@3.4.0
├── uid-safe@2.0.0 (base64-url@1.2.1)
└── debug@2.2.0 (ms@0.7.1)

grunt-mocha-test@0.12.7 node_modules/grunt-mocha-test
├── hooker@0.2.3
└── mkdirp@0.5.1 (minimist@0.0.8)

csurf@1.9.0 node_modules/csurf
├── cookie-signature@1.0.6
├── cookie@0.3.1
├── http-errors@1.5.0 (setprototypeof@1.0.1, inherits@2.0.1, statuses@1.3.0)
└── csrf@3.0.3 (rndm@1.2.0, base64-url@1.2.2, tsscmp@1.0.5, uid-safe@2.1.1)

helmet@0.9.1 node_modules/helmet
├── ienoopen@0.1.0
├── hide-powered-by@0.1.0
├── helmet-crossdomain@0.1.0
├── nocache@0.3.0
├── x-xss-protection@0.1.2
├── depd@1.0.1
├── frameguard@0.2.2 (lodash.isstring@3.0.1)
├── hpkp@0.1.0 (arraywrap@0.1.0)
├── hsts@0.1.3 (core-util-is@1.0.1)
├── helmet-csp@0.2.3 (camelize@1.0.0, core-util-is@1.0.1, platform@1.3.0)
└── connect@3.3.5 (utils-merge@1.0.0, parseurl@1.3.1, debug@2.1.3, finalhandler@0.3.4)

should@7.1.1 node_modules/should
├── should-type@0.2.0
├── should-equal@0.5.0
└── should-format@0.3.1

express@4.13.4 node_modules/express
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── fresh@0.3.0
├── escape-html@1.0.3
├── parseurl@1.3.1
├── array-flatten@1.1.1
├── etag@1.7.0
├── merge-descriptors@1.0.1
├── methods@1.1.2
├── range-parser@1.0.3
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── cookie@0.1.5
├── content-type@1.0.2
├── content-disposition@0.5.1
├── depd@1.1.0
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── send@0.13.1 (destroy@1.0.4, ms@0.7.1, statuses@1.2.1, mime@1.3.4, http-errors@1.3.1)
├── serve-static@1.10.3 (send@0.13.2)
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.11)

body-parser@1.15.1 node_modules/body-parser
├── bytes@2.3.0
├── content-type@1.0.2
├── depd@1.1.0
├── http-errors@1.4.0 (inherits@2.0.1, statuses@1.3.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── raw-body@2.1.6 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── qs@6.1.0
├── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)
└── iconv-lite@0.4.13

grunt-env@0.4.4 node_modules/grunt-env
├── ini@1.3.4
└── lodash@2.4.2

grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
├── gaze@0.5.2 (globule@0.1.0)
└── lodash@2.4.2

grunt-cli@0.1.13 node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)

zaproxy@0.2.0 node_modules/zaproxy
├── request@2.36.0 (aws-sign2@0.5.0, qs@0.6.6, forever-agent@0.5.2, tunnel-agent@0.4.3, oauth-sign@0.3.0, json-stringify-safe@5.0.1, mime@1.2.11, node-uuid@1.4.7, tough-cookie@2.2.2, form-data@0.1.4, http-signature@0.10.1, hawk@1.0.0)
└── lodash@2.4.2

mocha@2.5.3 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.0
├── growl@1.9.2
├── to-iso-string@0.0.2
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.2.0 (ms@0.7.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

grunt-retire@0.3.12 node_modules/grunt-retire
├── request@2.67.0 (tunnel-agent@0.4.3, is-typedarray@1.0.0, oauth-sign@0.8.2, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, json-stringify-safe@5.0.1, isstream@0.1.2, extend@3.0.0, form-data@1.0.0-rc4, node-uuid@1.4.7, combined-stream@1.0.5, qs@5.2.0, tough-cookie@2.2.2, mime-types@2.1.11, bl@1.0.3, http-signature@1.1.1, har-validator@2.0.6, hawk@3.1.3)
└── retire@1.1.5 (commander@2.5.1, walkdir@0.0.7, read-installed@4.0.3)

forever@0.14.2 node_modules/forever
├── colors@0.6.2
├── timespan@2.3.0
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── nssocket@0.5.3 (eventemitter2@0.4.14, lazy@1.0.11)
├── winston@0.8.3 (cycle@1.0.3, eyes@0.1.8, stack-trace@0.0.9, isstream@0.1.2, async@0.2.10, pkginfo@0.3.1)
├── cliff@0.1.10 (eyes@0.1.8, colors@1.0.3)
├── utile@0.2.1 (deep-equal@1.0.1, ncp@0.4.2, async@0.2.10, i@0.3.5, mkdirp@0.5.1, rimraf@2.5.2)
├── nconf@0.6.9 (ini@1.3.4, async@0.2.9, optimist@0.6.0)
├── forever-monitor@1.5.2 (watch@0.13.0, minimatch@1.0.0, ps-tree@0.0.3, broadway@0.3.6)
└── flatiron@0.4.3 (optimist@0.6.0, director@1.2.7, prompt@0.2.14, broadway@0.3.6)

grunt@0.4.5 node_modules/grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── getobject@0.1.0
├── eventemitter2@0.4.14
├── rimraf@2.2.8
├── colors@0.6.2
├── hooker@0.2.3
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── nopt@1.0.10 (abbrev@1.0.7)
├── exit@0.1.2
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.3)
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
├── grunt-legacy-log@0.1.3 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
└── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)

swig@1.4.2 node_modules/swig
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
└── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)

mongodb@2.1.18 node_modules/mongodb
├── es6-promise@3.0.2
├── readable-stream@1.0.31 (inherits@2.0.1, isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.2)
└── mongodb-core@1.3.18 (require_optional@1.0.0, bson@0.4.23)

grunt-nodemon@0.4.2 node_modules/grunt-nodemon
└── nodemon@1.9.2 (ignore-by-default@1.0.1, undefsafe@0.0.3, debug@2.2.0, es6-promise@3.2.1, touch@1.0.0, minimatch@3.0.0, lodash.defaults@3.1.2, ps-tree@1.1.0, update-notifier@0.5.0, chokidar@1.5.2)

grunt-jsbeautifier@0.2.12 node_modules/grunt-jsbeautifier
├── semver@5.1.0
├── rc@1.1.6 (ini@1.3.4, strip-json-comments@1.0.4, deep-extend@0.4.1, minimist@1.2.0)
├── underscore.string@3.3.4 (util-deprecate@1.0.2, sprintf-js@1.0.3)
├── async@2.0.0-rc.6
├── js-beautify@1.6.3 (nopt@3.0.6, config-chain@1.1.10, mkdirp@0.5.1)
└── lodash@4.13.1

grunt-contrib-jshint@0.11.3 node_modules/grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.8.0 (strip-json-comments@1.0.4, exit@0.1.2, shelljs@0.3.0, minimatch@2.0.10, console-browserify@1.1.0, cli@0.6.6, htmlparser2@3.8.3, lodash@3.7.0)

selenium-webdriver@2.47.0 node_modules/selenium-webdriver
├── tmp@0.0.24
├── adm-zip@0.4.4
├── rimraf@2.5.2 (glob@7.0.3)
├── xml2js@0.4.4 (xmlbuilder@8.2.2, sax@0.6.1)
└── ws@0.8.1 (options@0.0.6, ultron@1.0.2, utf-8-validate@1.2.1, bufferutil@1.2.1)

chromedriver@2.21.2 node_modules/chromedriver
├── kew@0.5.0
├── adm-zip@0.4.7
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rimraf@2.5.2 (glob@7.0.3)
└── npmconf@2.1.2 (ini@1.3.4, inherits@2.0.1, uid-number@0.0.5, once@1.3.3, semver@4.3.6, config-chain@1.1.10, nopt@3.0.6, osenv@0.1.3)
Step 1 : COPY . /usr/src/app
 ---> 3091bc578e9a
Removing intermediate container 24107bf7ac32
Removing intermediate container d21b334fae2f
Removing intermediate container b226d25d59a8
Step 2 : RUN node artifacts/db-reset.js
 ---> Running in e7cd9a069b1f
ERROR: connect
{"name":"MongoError","message":"connect ECONNREFUSED"}
Connected to the database: mongodb://localhost:27017/nodegoat
/usr/src/app/node_modules/mongodb/lib/server.js:231
        process.nextTick(function() { throw err; })
                                            ^
TypeError: Cannot read property 'dropCollection' of null
    at /usr/src/app/artifacts/db-reset.js:66:7
    at /usr/src/app/node_modules/mongodb/lib/mongo_client.js:238:20
    at /usr/src/app/node_modules/mongodb/lib/db.js:242:14
    at null.<anonymous> (/usr/src/app/node_modules/mongodb/lib/server.js:229:9)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:218:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (/usr/src/app/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:119:12)
ERROR: Service 'web' failed to build: The command '/bin/sh -c node artifacts/db-reset.js' returned a non-zero code: 1

**Comment by binarymist** [comment]
What version of node are you running?

**Comment by Ranybaug** [comment]
node --version
v5.0.0

**Comment by binarymist** [comment]
I don't think we've tested beyond 4.4. I can try with v5, but can't say when I'll have time to do this, alternatively you could try on v4.4 with NVM if you haven't already? Are you running on a Linux distro?

**Comment by binarymist** [comment]
The latest Dockerfile doesn't use 

> node:0.12-onbuild

This changed on https://github.com/OWASP/NodeGoat/commit/d1df52f66c5db7ecbd5cda9029d0b8c05dbf120b

I'd suggest making sure you're using the latest code. I'm also noticing your node_modules are all over the place. Some packages are older than what's specified in package.json and some newer. You will need to make sure that you have updated your packages with:
`npm install`

**Comment by binarymist** [comment]
Did you manage to make any progress on this @Ranybaug. Will be closing if you don't reply.

**Comment by ckarande** [comment]
Closing it due to lack of reply. @Ranybaug Please feel free to comment on it or create a new issue if the problem persists. Thanks @binarymist  for helping on it.
