### ISSUE TITLE
Not installing (node 6)

### ISSUE THREAD

**Issue by tb01923** [OWASP/NodeGoat#71]
This is not installing for me. chromedriver is having some sort of failure.  I have tried node 4,5,6 and posted the issue to their repository:

https://github.com/giggio/node-chromedriver/issues/46

**Comment by binarymist** [comment]
Did the suggested fix work at https://github.com/giggio/node-chromedriver/issues/46 @tb01923 ?

**Comment by binarymist** [comment]
Does this issue still need attention? Can we close it @tb01923 @ckarande ?

**Comment by jesusprubio** [comment]
It worked for me with the last stable (v6.6.0) and the last LTS (v4.5.0). I think we can close this.
