### ISSUE TITLE
Tutorial link in Readme is not working.

### ISSUE THREAD

**Issue by mkarvir** [OWASP/NodeGoat#93]
The link to Tutorial Guide (http://nodegoat.herokuapp.com/tutorial ) is not working. It would be great if this could be fixed. Thanks!

**Comment by ckarande** [comment]
@mkarvir Thanks for informing. It appears that Heroku platform itself is down right now. I am unable to login I will keep watch on it and try to bring the NodeGoat instance back up as soon as Heroku API is available.

**Comment by binarymist** [comment]
Trusty cloud platforms aye? My servers are still running fine.

**Comment by ckarande** [comment]
Ha.. I recently started admiring  AWS availability SLAs and this happened.

Node goat is back up. I am closing the issue.

**Comment by binarymist** [comment]
Yep, not everything that shines is golden. People are putting far to much trust in cloud providers. On-prem still has a lot of advantages, providing you have the specialties to admin it.

**Comment by mkarvir** [comment]
Thanks! May be this caused it -https://techcrunch.com/2017/02/28/amazon-aws-s3-outage-is-breaking-things-for-a-lot-of-websites-and-apps/
