### ISSUE TITLE
signup fails for hosted nodegoat

### ISSUE THREAD

**Issue by TomTasche** [OWASP/NodeGoat#97]
signup fails for the version of nodegoat hosted at http://nodegoat.herokuapp.com/

i have a feeling that this is intentional to save the database from being flooded with new users? if so, i think this should be documented in the README (or the hosted version itself?)

**Comment by ckarande** [comment]
@TomTasche the signup is failing due to some issue and it is not intentional..It must be broken because of any recent code or database on an inconsistent state. Either way, it is an issue and I will look into it. Thanks for reporting it.

**Comment by TomTasche** [comment]
thank you! fyi: when deploying it using the heroku deploy-button signup works just fine! if you send me the logs of the crash i can try to look into it

**Comment by ckarande** [comment]
@TomTasche The issue was caused due to inconsistent state of data in the DB. On resetting it, I could create new users.

**Comment by TomTasche** [comment]
thanks for taking your time to look into this!
