### ISSUE TITLE
Duplicate information in tutorial section A2

### ISSUE THREAD

**Issue by AdrianCohea** [OWASP/NodeGoat#98]
Hello,

I found in the tutorial section [A2 - 2 Password Guessing Attacks](https://nodegoat.herokuapp.com/tutorial/a2) contains information duplicated across a few subsections. The "How Do I Prevent It?" subsection contains the following sentences:

> Authentication failure responses should not indicate which part of the authentication data was incorrect. For example, instead of "Invalid username" or "Invalid password", just use "Invalid username and/or password" for both. Error responses must be truly identical in both display and source code

These are also in the "Additional Measures" subsection. I recommend removing the second bullet point. In my opinion, this information is important enough not to be considered additional, especially since it already has its own subsection.

Thanks for creating this application and tutorial for people new to the application security space!

**Comment by ckarande** [comment]
@AdrianCohea Thanks for the suggestion.
